name: khorochi
description: "A premium smart grocery and household shopping list with expense tracking."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter


  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  flutter_svg: ^2.2.4
  lucide_icons: ^0.257.0

  # State Management (Riverpod)
  riverpod: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/khorochi_logo.png"
  min_sdk_android: 21

   # Android adaptive icon configuration
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/khorochi_logo.png"
  
  # iOS configuration
  remove_alpha_ios: true


flutter:

  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

